id: I4CB932A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:00:55+00:00'
last_modified: '2022-06-07T20:46:08.731463+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10288
  title: ཕྱག་ཆེན་ལྔ་ལྡན་དྷརྨ་ཀཱིརྟི་ཞལ་ལུང་དང་ཆོས་དྲུག་ནཱ་རོའི་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC07:
      image_group_id: I1KG10343
      title: ''
      total_pages: 492
      order: 1
      base_file: CC07.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
