id: P004169
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:58.519446
source_metadata:
  id: bdr:W1KG10288
  title: ཕྱག་ཆེན་ལྔ་ལྡན་དྷརྨ་ཀཱིརྟི་ཞལ་ལུང་དང་ཆོས་དྲུག་ནཱ་རོའི་ཞལ་ལུང་།
  author: ''
  volumes:
    1ebc6715d8f64caaa3975ff9e0e2bb8a:
      image_group_id: I1KG10343
      title: ''
      volume_number: 1
      total_pages: 492
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
